name: build and push
on:
  push:


permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    name: build & deploy
    runs-on:
      - self-hosted

    environment: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: building and setting local environment on server

        run:
          docker-compose -f ./docker-compose/docker-compose.yml -p mapbook_gk2 up --build -d


